### ISSUE TITLE
API website: 'improve docs' link leads to 404

### ISSUE THREAD

**Issue by tombohub** [ScottPlot/ScottPlot.NET#32]
Clicking on `Improve this Doc`  on page https://scottplot.net/doc/v4/api/ leads to github 404

**Comment by swharden** [comment]
Thanks for reporting this @tombohub!

I'll probably fix the url so we know how for the future, then temporarily disable the API website because it's overwhelmingly complex. I'd like to make the API docs with something custom/simpler, and in the meantime we can lean on FuGet if we really need to refer to a method signature or something like that https://www.fuget.org/packages/ScottPlot/
