### ISSUE TITLE
libgdiplus

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot.NET#4]
somewhere in the recent website transition information about `apt-get install -y libgdiplus` was lost

**Comment by bclehmann** [comment]
I don't know if this has been fixed yet, but this should be added to Eto when it's added to the docs. Also probably a note about adding `System.Drawing.Common` to the .csproj

**Comment by royalstream** [comment]
Using .NET 6.0, macOS 12.1, ScottPlot.Avalonia/4.1.29 I get the following error:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. 
```

After running `brew install mono-libgdiplus` as indicated [here](https://github.com/ScottPlot/ScottPlot/issues/661) I get the plot to display but it shows some weird Chinese characters instead of numbers on each axis.

**Comment by bclehmann** [comment]
I think installing `System.Common.Drawing` using `dotnet add package System.Common.Drawing` will help.

**Comment by royalstream** [comment]
`System.Drawing.Common` is only supported on Windows.

**Comment by swharden** [comment]
> System.Drawing.Common is not supported on non-Windows platforms

@royalstream this is only true with .NET 6 - the System.Drawing.Common package is supported on Linux and MacOS on .NET Framework 4.6.1-4.8 and .NET Core through .NET 5. A temporary solution could be to target your project for .NET 5 👍 

#1036 attempts to solve this for .NET 6 and newer by migrating to Microsoft.Maui.Graphics but that library is not mature yet...

**Comment by swharden** [comment]
> > System.Drawing.Common is not supported on non-Windows platforms

> this is only true with .NET 6

... Actually, this information should be added to the quickstarts too

**Comment by royalstream** [comment]
I already downgraded to .NET 5.0 and I get the same behavior.
I don't think it's related to missing DLLs because the program compiles and it displays the graphic correctly (under both .NET 6.0 and 5.0).
The problem is only related to the fonts and I strongly suspect it's related to Unicode.
For example, if I add a label to the XAxis:

`avaPlot1.Plot.XAxis.Label(label: "ABCDE", fontName: "Arial", size: 24, color: Color.Red, bold: true);` 

The label displays something like **E instead of ABCDE (where * stands for some weird Chinese character)
Changing the font makes no difference.

If I make the label exactly one character like "A" or "1" it works too.

If I change the label to "123456789" it shows like ****9**

**Comment by swharden** [comment]
Hi @royalstream, 

This issue sounds very similar to https://github.com/ScottPlot/ScottPlot/issues/1220 

Can you open an issue over on https://github.com/ScottPlot/ScottPlot/issues (this repo is just for the website) and include a screenshot and the sample code used to make it? I think there's a sample console program there which can reproduce the issue in just 3 lines https://github.com/ScottPlot/ScottPlot/issues/1220#issuecomment-904233580 - I'd be interested to see the output of that program on your system. Posting the content of your `csproj` file would be helpful too!

**Comment by royalstream** [comment]
Problem solved. And it works under both .NET 5.0 and .NET 6.0.

I was running into [issue 1079](https://github.com/ScottPlot/ScottPlot/issues/1079).

The following snippet works great as long as I don't add a reference to ScottPlot.

```c#
Bitmap bmp = new Bitmap(200, 100);
using var gfx = Graphics.FromImage(bmp);
gfx.Clear(Color.Navy);
Font fnt = new Font("Arial", 18);
gfx.DrawString("test123", fnt, Brushes.Yellow, 10, 10);
bmp.Save("test.bmp");
```

As you all suspected, **System.Drawing.Common** was the culprit. 

This is the version it uses by default (no reference to ScottPlot):

```
System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
/.nuget/packages/system.drawing.common/4.5.0/ref/netstandard2.0/System.Drawing.Common.dll
```

And this is the version ScottPlot brings to the party (causing the problem): 

```
System.Drawing.Common, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
/.nuget/packages/system.drawing.common/4.6.1/ref/netcoreapp3.0/System.Drawing.Common.dll

```

I cannot add a reference to the latest System.Drawing.Common (6.0.0) because I get a PlatformNotSupportedException.

So I tried using version **5.0.2** like they mentioned [in the comments](https://github.com/ScottPlot/ScottPlot/issues/1079#issuecomment-849919035) and voilá! that did it. 

Thank you all.

**Comment by swharden** [comment]
Awesome, I'm glad you got this to work! Thanks for following-up here and in #1079 with your solution 🚀 

System.Drawing can be touchy and I will be happy to leave it behind in a future version of this library 😅
